"""Overview critic: judges a whole checkpoint sequence from one composed grid image."""

from __future__ import annotations

import base64
import json
import logging
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from foldingagent import config
from foldingagent.backends.base import (
    _load_dotenv_into_env,
    _mime_type_for_path,
    _provider_for_model,
    _resolve_api_key,
)
from foldingagent.logger import _save_critic_call
from foldingagent.prompt_assembler import build_overview_critic_prompt, build_overview_instruction

logger = logging.getLogger(__name__)

_MAX_OUTPUT_TOKENS = config.MAX_OUTPUT_TOKENS


@dataclass
class OverviewCriticResponse:
    last_correct_frame: int | None
    first_suspicious_frame: int | None
    analysis: str
    per_frame_notes: list[str] = field(default_factory=list)


class OrigamiOverviewCritic:
    """
    Stateless specialist for checkpoint overview analysis.

    Each call to ``evaluate`` is an independent single-turn request with no
    memory of previous evaluations.  The specialist analyzes a multi-column
    overview grid (frame labels / real photos / rendered diagrams) and
    identifies the last frame where the diagram still correctly matches the photo.

    Supports the same three providers as :class:`OrigamiCritic` (dispatched by
    ``model``), so it can share the main agent's model and API key.
    """

    def __init__(
        self,
        model: str = config.DEFAULT_MODEL,
        system_prompt: str | None = None,
    ) -> None:
        self.model = model
        self.system_prompt = system_prompt or build_overview_critic_prompt()
        self.provider = _provider_for_model(model)
        self.log_dir: Path | None = None

        _load_dotenv_into_env()

        if self.provider == "anthropic":
            try:
                import anthropic as _anthropic  # type: ignore[import]
            except ImportError as exc:
                raise ImportError(
                    "Install the Anthropic SDK:  pip install anthropic"
                ) from exc
            _api_key = _resolve_api_key("anthropic")
            self._client = _anthropic.Anthropic(api_key=_api_key)
        elif self.provider == "openai":
            try:
                import openai as _openai  # type: ignore[import]
            except ImportError as exc:
                raise ImportError(
                    "Install the OpenAI SDK:  pip install openai"
                ) from exc
            _api_key = _resolve_api_key("openai")
            self._client = _openai.OpenAI(api_key=_api_key)
        else:
            try:
                from google import genai as _genai  # type: ignore[import]
            except ImportError as exc:
                raise ImportError(
                    "Install the Google GenAI SDK:  pip install google-genai"
                ) from exc

            _api_key = _resolve_api_key("gemini")
            self._client = _genai.Client(api_key=_api_key)

    def _overview_instruction(self, frame_indices: list[int]) -> str:
        return build_overview_instruction(frame_indices)

    def evaluate(
        self,
        overview_path: Path,
        frame_indices: list[int],
    ) -> OverviewCriticResponse:
        """
        Analyze the checkpoint overview grid and return the last correct frame.

        Parameters
        ----------
        overview_path:
            Path to the overview PNG generated by generate_checkpoint_overview().
        frame_indices:
            Ordered list of frame indices shown in the overview (left → right).
        """
        if self.provider == "anthropic":
            raw_text = self._call_anthropic(overview_path, frame_indices)
        elif self.provider == "openai":
            raw_text = self._call_openai(overview_path, frame_indices)
        else:
            raw_text = self._call_gemini(overview_path, frame_indices)

        if self.log_dir is not None:
            _save_critic_call(
                self.log_dir,
                {
                    "model": self.model,
                    "overview_path": str(overview_path),
                    "frame_indices": frame_indices,
                    "system_prompt": self.system_prompt,
                },
                {"raw_text": raw_text},
                "overview_critic",
            )

        return self._parse_response(raw_text, frame_indices)

    def _call_gemini(self, overview_path: Path, frame_indices: list[int]) -> str:
        from google.genai import types as gtypes  # type: ignore[import]

        try:
            image_bytes = overview_path.read_bytes()
        except OSError as exc:
            raise RuntimeError(f"Cannot read overview image {overview_path}: {exc}") from exc

        parts = [
            gtypes.Part.from_bytes(data=image_bytes, mime_type="image/png"),
            gtypes.Part.from_text(text=self._overview_instruction(frame_indices)),
        ]

        response = self._client.models.generate_content(
            model=self.model,
            contents=[{"role": "user", "parts": parts}],
            config=gtypes.GenerateContentConfig(
                system_instruction=self.system_prompt,
            ),
        )

        raw_text = ""
        if response and response.candidates:
            for part in response.candidates[0].content.parts or []:
                if hasattr(part, "text") and part.text:
                    raw_text += part.text
        return raw_text

    def _call_anthropic(self, overview_path: Path, frame_indices: list[int]) -> str:
        try:
            image_bytes = overview_path.read_bytes()
        except OSError as exc:
            raise RuntimeError(f"Cannot read overview image {overview_path}: {exc}") from exc

        content = [
            {
                "type": "image",
                "source": {
                    "type": "base64",
                    "media_type": _mime_type_for_path(overview_path),
                    "data": base64.standard_b64encode(image_bytes).decode(),
                },
            },
            {"type": "text", "text": self._overview_instruction(frame_indices)},
        ]

        kwargs: dict[str, Any] = {
            "model": self.model,
            "max_tokens": _MAX_OUTPUT_TOKENS,
            "system": self.system_prompt,
            "messages": [{"role": "user", "content": content}],
        }

        response = self._client.messages.create(**kwargs)

        raw_text = ""
        if response is not None:
            for block in response.content:
                if getattr(block, "type", "") == "text" and getattr(block, "text", None):
                    raw_text += block.text
        return raw_text

    def _call_openai(self, overview_path: Path, frame_indices: list[int]) -> str:
        try:
            image_bytes = overview_path.read_bytes()
        except OSError as exc:
            raise RuntimeError(f"Cannot read overview image {overview_path}: {exc}") from exc

        b64 = base64.standard_b64encode(image_bytes).decode()
        content = [
            {
                "type": "image_url",
                "image_url": {"url": f"data:{_mime_type_for_path(overview_path)};base64,{b64}"},
            },
            {"type": "text", "text": self._overview_instruction(frame_indices)},
        ]

        messages = [
            {"role": "system", "content": self.system_prompt},
            {"role": "user", "content": content},
        ]

        kwargs: dict[str, Any] = {
            "model": self.model,
            "max_completion_tokens": _MAX_OUTPUT_TOKENS,
            "messages": messages,
        }

        response = self._client.chat.completions.create(**kwargs)

        raw_text = ""
        if response is not None and response.choices:
            message_content = response.choices[0].message.content
            if message_content:
                raw_text = message_content
        return raw_text

    def _parse_response(self, raw_text: str, frame_indices: list[int]) -> OverviewCriticResponse:
        text = raw_text.strip()
        if text.startswith("```"):
            lines = text.splitlines()
            text = "\n".join(
                line for line in lines if not line.strip().startswith("```")
            ).strip()

        try:
            data = json.loads(text)
            lcf = data.get("last_correct_frame")
            fsf = data.get("first_suspicious_frame")
            return OverviewCriticResponse(
                last_correct_frame=int(lcf) if lcf is not None else None,
                first_suspicious_frame=int(fsf) if fsf is not None else None,
                analysis=str(data.get("analysis", raw_text)),
                per_frame_notes=[str(n) for n in data.get("per_frame_notes", [])],
            )
        except (json.JSONDecodeError, KeyError, ValueError) as exc:
            logger.warning("Overview critic JSON parse failed: %s", exc)
            return OverviewCriticResponse(
                last_correct_frame=frame_indices[-1] if frame_indices else None,
                first_suspicious_frame=None,
                analysis=raw_text or "Overview critic returned no response.",
                per_frame_notes=[],
            )


def build_checkpoint_overview_image(
    *,
    sorted_frames: list[int],
    frame_paths: list[Path | None],
    diagram_paths: list[Path],
    out_path: Path,
) -> Path:
    """Compose the label / photo / diagram overview grid this critic evaluates.

    One column per checkpointed frame, left=earliest. Row 0 is the frame index,
    row 1 the real photo, row 2 the rendered diagram, separated by a 2-px grid.
    """
    from PIL import Image, ImageDraw, ImageFont

    panel = 256
    grid_w = 2
    label_h = 110
    font_size = 64
    n = len(sorted_frames)

    def _load_rgb_image(image_path: Path) -> Image.Image:
        with Image.open(image_path) as image:
            if image.mode in {"RGBA", "LA"}:
                background = Image.new("RGBA", image.size, "white")
                return Image.alpha_composite(
                    background,
                    image.convert("RGBA"),
                ).convert("RGB")
            return image.convert("RGB")

    photo_row_heights: list[int] = []
    for frame_n in sorted_frames:
        frame_path = frame_paths[sorted_frames.index(frame_n)]
        if frame_path is None or not frame_path.exists():
            photo_row_heights.append(panel)
            continue
        with Image.open(frame_path) as photo:
            width, height = photo.size
        if width <= 0 or height <= 0:
            photo_row_heights.append(panel)
            continue
        scaled_height = max(1, round(height * (panel / width)))
        photo_row_heights.append(scaled_height)

    photo_row_h = max(photo_row_heights, default=panel)

    # Try to load a small font; fall back to default
    try:
        for _candidate in (
            "/usr/share/fonts/dejavu-sans-fonts/DejaVuSans-Bold.ttf",
            "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf",
            "/usr/share/fonts/liberation/LiberationSans-Bold.ttf",
            "/usr/share/fonts/truetype/liberation/LiberationSans-Bold.ttf",
            "/usr/share/fonts/dejavu-sans-fonts/DejaVuSans.ttf",
            "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf",
            "/usr/share/fonts/liberation/LiberationSans-Regular.ttf",
            "/usr/share/fonts/truetype/liberation/LiberationSans-Regular.ttf",
        ):
            if Path(_candidate).exists():
                font = ImageFont.truetype(_candidate, font_size)
                break
        else:
            font = ImageFont.load_default()
    except Exception:
        font = ImageFont.load_default()

    total_w = n * panel + (n + 1) * grid_w
    total_h = label_h + grid_w + photo_row_h + grid_w + panel + grid_w

    canvas = Image.new("RGB", (total_w, total_h), (50, 50, 50))
    draw = ImageDraw.Draw(canvas)

    for col, (frame_n, diag_path) in enumerate(zip(sorted_frames, diagram_paths)):
        cell_x = grid_w + col * (panel + grid_w)

        # Label bar
        label = str(frame_n)
        draw.rectangle((cell_x, 0, cell_x + panel - 1, label_h - 1), fill=(30, 30, 30))
        try:
            bb = draw.textbbox((0, 0), label, font=font)
            tw = bb[2] - bb[0]
            th = bb[3] - bb[1]
        except AttributeError:
            tw, th = draw.textsize(label, font=font)
        draw.text(
            (cell_x + (panel - tw) // 2, (label_h - th) // 2),
            label, fill=(220, 220, 220), font=font,
        )

        # Photo row
        photo_y = label_h + grid_w
        draw.rectangle(
            (cell_x, photo_y, cell_x + panel - 1, photo_y + photo_row_h - 1),
            fill=(255, 255, 255),
        )
        frame_path = frame_paths[sorted_frames.index(frame_n)]
        if frame_path and frame_path.exists():
            photo = _load_rgb_image(frame_path)
            scaled_height = photo_row_heights[col]
            photo = photo.resize((panel, scaled_height), Image.LANCZOS)
            photo_top = photo_y + (photo_row_h - scaled_height) // 2
            canvas.paste(photo, (cell_x, photo_top))

        # Diagram row
        diag_y = label_h + grid_w + photo_row_h + grid_w
        draw.rectangle(
            (cell_x, diag_y, cell_x + panel - 1, diag_y + panel - 1),
            fill=(255, 255, 255),
        )
        if diag_path.exists():
            diag = _load_rgb_image(diag_path).resize((panel, panel), Image.LANCZOS)
            canvas.paste(diag, (cell_x, diag_y))

    # Draw vertical grid lines
    for col in range(n + 1):
        x = col * (panel + grid_w)
        draw.rectangle((x, 0, x + grid_w - 1, total_h - 1), fill=(0, 0, 0))

    # Draw horizontal grid lines
    for y in (
        label_h,
        label_h + grid_w + photo_row_h,
        label_h + grid_w + photo_row_h + grid_w + panel,
    ):
        draw.rectangle((0, y, total_w - 1, y + grid_w - 1), fill=(0, 0, 0))
    canvas.save(str(out_path), format="PNG")
    return out_path
